apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: deanery.com
      http:
        paths:
          - path: /api/auth/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
          - path: /api/groups/?(.*)
            pathType: Prefix
            backend:
              service:
                name: students-srv
                port:
                  number: 3000
          - path: /api/specialities/?(.*)
            pathType: Prefix
            backend:
              service:
                name: students-srv
                port:
                  number: 3000
          - path: /api/streams/?(.*)
            pathType: Prefix
            backend:
              service:
                name: students-srv
                port:
                  number: 3000
          - path: /api/students/?(.*)
            pathType: Prefix
            backend:
              service:
                name: students-srv
                port:
                  number: 3000
          - path: /api/dean-applications/?(.*)
            pathType: Prefix
            backend:
              service:
                name: students-srv
                port:
                  number: 3000
